version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: swarm_rabbitmq
    ports:
      - "5672:5672"   # Cổng cho code Python giao tiếp (AMQP)
      - "15672:15672" # Cổng giao diện Web
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin123"
    restart: always